// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'utils/collections_test.dart' as utils_collections_test;
import 'utils/string_utils_test.dart' as utils_string_utils_test;

void main() {
  utils_collections_test.main();
  utils_string_utils_test.main();
}
